[pytest]
markers =
    slow: slow unit tests.
    integration: integration tests.
    notebook: tests that can only run with a completed robominnie notebook (after integration tests).
addopts = -xm "not slow and not integration and not notebook" -W ignore::pydantic.PydanticDeprecatedSince20
