name: CI

# Trigger on commits.
on:
  push:

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version:
          - "3.11"
          - "3.12"
    name: Tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install default dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-torch.txt

      - name: Install coppafisher
        run: python -m pip install .

      - name: Verify coppafisher import
        run: python -Ic "import coppafisher"

      - name: Install dev packages
        run: python -m pip install -r requirements-dev.txt

      - name: Run default unit tests
        run: pytest -m "not integration and not notebook" --cov=coppafisher --cov-report term

      - name: Run default integration tests
        run: pytest -m "integration" --cov=coppafisher --cov-report term

      - name: Run notebook-dependent tests
        run: pytest -m "notebook" --cov=coppafisher --cov-report term
