name: Version Bump Check

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install default dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-torch.txt

      - name: Install coppafisher
        run: python -m pip install .

      - name: Assert version bump
        run: |
          python -Ic "from coppafisher.utils import system; online_version = system.get_remote_software_version(); assert online_version is not None; assert online_version != system.get_software_version()"
